name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL_PROD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get OIDC Id Token
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            return await core.getIDToken();
          result-encoding: string

      - name: Build & Deploy (OIDC)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: ./frontend
          output_location: dist
          github_id_token: ${{ steps.oidc.outputs.result }}
