name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL_PROD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Deploy (token)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_FIELD_0C0C20310 }}
          action: upload
          app_location: ./frontend
          output_location: dist
