name: backend-ci  # CI for the FastAPI backend

on:
  # Run on PRs that touch backend/ or this workflow
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  # Also run after merges to main that touch backend/ or this workflow
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest

    # All shell steps below run inside backend/
    defaults:
      run:
        working-directory: backend

    steps:
      # 1) Check out repo at the PR commit
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Use the same Python you run on the VM
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      # 3) Provide a dummy .env if an example exists (avoids missing-env crashes)
      - name: Prepare .env
        run: |
          if [ -f .env.example ] && [ ! -f .env ]; then cp .env.example .env; fi

      # 4) Install backend dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 5) Smoke check: can we import your app entrypoint?
      - name: Import app.main
        run: |
          python - << 'PY'
          import importlib, sys
          try:
              importlib.import_module('app.main')
              print("OK: import app.main")
          except Exception as e:
              print("FAIL:", e)
              sys.exit(1)
          PY

      # 6) Run tests only if a tests/ folder exists
      - name: Run tests (if present)
        if: ${{ hashFiles('backend/tests/**') != '' }}
        run: pytest -q
